# Generated by Django 5.1.7 on 2025-03-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="redactor",
            name="year_of_experience",
            field=models.IntegerField(null=True),
        ),
    ]
